api_platform:
  eager_loading:
    max_joins: 100
  title: AIS API
  version: 0.1.1

  mapping:
    paths: [
      '%kernel.project_dir%/App/mod_education/Entity',
      '%kernel.project_dir%/App/MainApp/Entity',
      '%kernel.project_dir%/App/mod_mosregvis/Entity',
      '%kernel.project_dir%/App/mod_admission/Entity'

    ]
  patch_formats:
    json: [ 'application/merge-patch+json' ]
  defaults:
    stateless: true
    cache_headers:
      vary: [ 'Content-Type', 'Authorization', 'Origin' ]
