doctrine:
    dbal:
        types:
            snils: Npub\Gos\Doctrine\Type\SnilsType
            snils_canonical: Npub\Gos\Doctrine\Type\SnilsCanonicalType
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/App/MainApp/Entity'
                prefix: 'App\MainApp\Entity'
                alias: MainApp
            StudentApp:
                is_bundle: false
                dir: '%kernel.project_dir%/App/mod_student_app/Entity'
                prefix: 'App\mod_student_app\Entity'
                alias: mod_student_app
            mod_mosregvis:
                is_bundle: false
                dir: '%kernel.project_dir%/App/mod_mosregvis/Entity'
                prefix: 'App\mod_mosregvis\Entity'
                alias: mod_mosregvis
            mod_education:
                is_bundle: false
                dir: '%kernel.project_dir%/App/mod_education/Entity'
                prefix: 'App\mod_education\Entity'
                alias: mod_ed    ucation
            mod_admission:
                is_bundle: false
                dir: '%kernel.project_dir%/App/mod_admission/Entity'
                prefix: 'App\mod_admission\Entity'
                alias: mod_admission
            mod_events:
                is_bundle: false
                dir: '%kernel.project_dir%/App/mod_events/Entity'
                prefix: 'App\mod_events\Entity'
                alias: mod_events
            mod_prof_education:
                is_bundle: false
                dir: '%kernel.project_dir%/App/mod_prof_education/Entity'
                prefix: 'App\mod_events\Entity'
                alias: mod_prof_education
            global:
                is_bundle: false
                dir: '%kernel.project_dir%/App/Global/Entity'
                prefix: 'App\Global\Entity'
                alias: global
            security:
                is_bundle: false
                dir: '%kernel.project_dir%/App/MainApp/Security/Entity'
                prefix: 'App\MainApp\Security\Entity'
                alias: security
        filters:
            studentFilter:
                class: App\mod_education\Doctrine\Filter\StudentFilter
                enabled: false
                parameters:
                    discontinued: false
            studentGroupFilter:
                class: App\MainApp\Doctrine\Filter\studentGroupFilter
                enabled: false
                parameters:
                    discontinued: false
            EventsResultFilter:
                class: App\MainApp\Doctrine\Filter\EventsResultFilter
                enabled: false
                parameters:
                    discontinued: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
