<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20241031134334 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE abiturient_petition_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE abiturient_petition_status_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE access_system_control_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE admission_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE admission_examination_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE admission_examination_result_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE admission_examination_subjects_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE admission_plan_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE admission_status_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE app_configuration_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE characteristic_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE college_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE contingent_document_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE contingent_document_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE education_form_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE education_plan_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE education_semester_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE education_subjects_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE education_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE education_year_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE events_category_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE events_level_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE events_list_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE events_places_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE events_result_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE events_result_types_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE faculty_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE family_type_list_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE financial_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE gender_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE group_membership_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE health_group_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE legal_representative_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE legal_representative_type_list_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE login_provider_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE login_values_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE mod_mosreg_vis_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE person_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE personal_doc_type_list_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE personal_documents_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE reference_edu_year_status_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE reference_spo_education_year_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE reference_spo_speciality_dictionary_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE reference_study_discipline_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE reference_training_program_gradation_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE reference_uftt_document_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE regions_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE roles_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE social_network_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE social_network_type_list_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE specialization_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE staff_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE student_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE student_groups_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE student_punishment_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE system_services_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE "user_id_seq" INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE abiturient_petition (id INT NOT NULL, gender_id INT DEFAULT NULL, status_id INT DEFAULT NULL, admission_id INT DEFAULT NULL, faculty_id INT DEFAULT NULL, region_id INT DEFAULT NULL, admission_plan_position_id INT DEFAULT NULL, person_id INT DEFAULT NULL, guid VARCHAR(255) NOT NULL, number VARCHAR(255) NOT NULL, middle_name VARCHAR(255) DEFAULT NULL, created_ts TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, registration_address TEXT DEFAULT NULL, current_location_address TEXT DEFAULT NULL, birth_place TEXT DEFAULT NULL, pasport_issue_organ TEXT DEFAULT NULL, document_obtained BOOLEAN DEFAULT NULL, upload_ts TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_update_ts TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, local_number INT DEFAULT NULL, education_document_gpa DOUBLE PRECISION DEFAULT NULL, canceled BOOLEAN DEFAULT NULL, pasport_series VARCHAR(10) DEFAULT NULL, pasport_number INT DEFAULT NULL, pasport_date_obtain DATE DEFAULT NULL, load_to_fisgia BOOLEAN DEFAULT NULL, comment TEXT DEFAULT NULL, can_pay BOOLEAN DEFAULT NULL, school_name TEXT DEFAULT NULL, education_document_name VARCHAR(255) DEFAULT NULL, education_document_number VARCHAR(255) DEFAULT NULL, have_error_in_petition BOOLEAN DEFAULT NULL, number_provision INT DEFAULT NULL, date_provision DATE DEFAULT NULL, number_cancel INT DEFAULT NULL, date_cancel DATE DEFAULT NULL, cancel_reason TEXT DEFAULT NULL, is_orphan BOOLEAN DEFAULT NULL, is_invalid BOOLEAN DEFAULT NULL, is_poor BOOLEAN DEFAULT NULL, need_student_accommondation BOOLEAN DEFAULT NULL, attaches JSON DEFAULT NULL, lock_update_form_vis BOOLEAN DEFAULT NULL, potok VARCHAR(255) DEFAULT NULL, has_target_agreement BOOLEAN DEFAULT NULL, target_agreement_number VARCHAR(255) DEFAULT NULL, target_agreement_date DATE DEFAULT NULL, target_agreement_employer TEXT DEFAULT NULL, is_blocked_to_edit BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_50A0C6E5708A0E0 ON abiturient_petition (gender_id)');
        $this->addSql('CREATE INDEX IDX_50A0C6E56BF700BD ON abiturient_petition (status_id)');
        $this->addSql('CREATE INDEX IDX_50A0C6E575C9C554 ON abiturient_petition (admission_id)');
        $this->addSql('CREATE INDEX IDX_50A0C6E5680CAB68 ON abiturient_petition (faculty_id)');
        $this->addSql('CREATE INDEX IDX_50A0C6E598260155 ON abiturient_petition (region_id)');
        $this->addSql('CREATE INDEX IDX_50A0C6E54452387F ON abiturient_petition (admission_plan_position_id)');
        $this->addSql('CREATE INDEX IDX_50A0C6E5217BBB47 ON abiturient_petition (person_id)');
        $this->addSql('CREATE TABLE abiturient_petition_status (id INT NOT NULL, title VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE access_system_control (id INT NOT NULL, student_id INT DEFAULT NULL, access_card_series INT NOT NULL, acces_card_number INT NOT NULL, issue_date DATE NOT NULL, is_locked BOOLEAN DEFAULT NULL, lock_date DATE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_3D33BA65CB944F1A ON access_system_control (student_id)');
        $this->addSql('CREATE TABLE admission (id INT NOT NULL, status_id INT DEFAULT NULL, college_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, date_start DATE DEFAULT NULL, date_end DATE DEFAULT NULL, is_active BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F4BB024A6BF700BD ON admission (status_id)');
        $this->addSql('CREATE INDEX IDX_F4BB024A770124B2 ON admission (college_id)');
        $this->addSql('CREATE TABLE admission_examination (id INT NOT NULL, faculty_id INT DEFAULT NULL, examination_subject_id INT DEFAULT NULL, admission_plan_position_id INT DEFAULT NULL, date DATE NOT NULL, pass_score DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_AD531D33680CAB68 ON admission_examination (faculty_id)');
        $this->addSql('CREATE INDEX IDX_AD531D334C13C434 ON admission_examination (examination_subject_id)');
        $this->addSql('CREATE INDEX IDX_AD531D334452387F ON admission_examination (admission_plan_position_id)');
        $this->addSql('CREATE TABLE admission_examination_result (id INT NOT NULL, abiturient_petition_id INT DEFAULT NULL, admission_examination_id INT DEFAULT NULL, mark DOUBLE PRECISION NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C28FCD9821E040B ON admission_examination_result (abiturient_petition_id)');
        $this->addSql('CREATE INDEX IDX_C28FCD94D62F206 ON admission_examination_result (admission_examination_id)');
        $this->addSql('CREATE TABLE admission_examination_subjects (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE admission_plan (id INT NOT NULL, admission_id INT DEFAULT NULL, faculty_id INT DEFAULT NULL, target_count INT DEFAULT NULL, have_admission_examination BOOLEAN DEFAULT false, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_81EE964D75C9C554 ON admission_plan (admission_id)');
        $this->addSql('CREATE INDEX IDX_81EE964D680CAB68 ON admission_plan (faculty_id)');
        $this->addSql('CREATE TABLE admission_status (id INT NOT NULL, name VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE app_configuration (id INT NOT NULL, initial_complete BOOLEAN NOT NULL, app_language VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE characteristic (id INT NOT NULL, student_id INT DEFAULT NULL, create_data DATE NOT NULL, content TEXT DEFAULT NULL, answers JSON DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_522FA950CB944F1A ON characteristic (student_id)');
        $this->addSql('CREATE TABLE college (id INT NOT NULL, name TEXT NOT NULL, short_name VARCHAR(255) NOT NULL, postal_address TEXT NOT NULL, registered_address TEXT NOT NULL, email VARCHAR(255) NOT NULL, web_site VARCHAR(255) NOT NULL, logo TEXT NOT NULL, phone VARCHAR(13) NOT NULL, fax VARCHAR(13) NOT NULL, settings_staff_domain VARCHAR(255) DEFAULT NULL, settings_students_domain VARCHAR(255) DEFAULT NULL, dtype VARCHAR(255) NOT NULL, vis_college_id VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE contingent_document (id INT NOT NULL, type_id INT DEFAULT NULL, college_id INT DEFAULT NULL, number VARCHAR(255) NOT NULL, create_date DATE NOT NULL, is_active BOOLEAN NOT NULL, name VARCHAR(255) DEFAULT NULL, reason TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_672BE59BC54C8C93 ON contingent_document (type_id)');
        $this->addSql('CREATE INDEX IDX_672BE59B770124B2 ON contingent_document (college_id)');
        $this->addSql('CREATE TABLE contingent_document_student (contingent_document_id INT NOT NULL, student_id INT NOT NULL, PRIMARY KEY(contingent_document_id, student_id))');
        $this->addSql('CREATE INDEX IDX_A66031F118B26CAF ON contingent_document_student (contingent_document_id)');
        $this->addSql('CREATE INDEX IDX_A66031F1CB944F1A ON contingent_document_student (student_id)');
        $this->addSql('CREATE TABLE contingent_document_type (id INT NOT NULL, name VARCHAR(255) NOT NULL, title VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE education_form (id INT NOT NULL, name VARCHAR(255) NOT NULL, title VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE education_plan (id INT NOT NULL, faculty_id INT DEFAULT NULL, education_form_id INT DEFAULT NULL, base_education_type_id INT DEFAULT NULL, date_start DATE DEFAULT NULL, date_end DATE DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, qualification VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_37C3E6CC680CAB68 ON education_plan (faculty_id)');
        $this->addSql('CREATE INDEX IDX_37C3E6CC43D2F4A5 ON education_plan (education_form_id)');
        $this->addSql('CREATE INDEX IDX_37C3E6CC7FE0B941 ON education_plan (base_education_type_id)');
        $this->addSql('CREATE TABLE education_semester (id INT NOT NULL, education_year_id INT DEFAULT NULL, education_plan_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7F2CF0645CE5917F ON education_semester (education_year_id)');
        $this->addSql('CREATE INDEX IDX_7F2CF064F4BD6D43 ON education_semester (education_plan_id)');
        $this->addSql('CREATE TABLE education_subjects (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE education_type (id INT NOT NULL, name VARCHAR(255) NOT NULL, title VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE education_year (id INT NOT NULL, title VARCHAR(255) NOT NULL, date_start DATE NOT NULL, date_end DATE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE events_category (id INT NOT NULL, name VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE events_level (id INT NOT NULL, name VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE events_list (id INT NOT NULL, event_category_id INT DEFAULT NULL, event_level_id INT DEFAULT NULL, event_place_id INT DEFAULT NULL, name TEXT NOT NULL, event_date DATE NOT NULL, is_group_event BOOLEAN NOT NULL, event_start_time TIME(0) WITHOUT TIME ZONE NOT NULL, event_end_time TIME(0) WITHOUT TIME ZONE NOT NULL, comment TEXT DEFAULT NULL, is_public BOOLEAN NOT NULL, is_can_have_results BOOLEAN DEFAULT NULL, is_archived BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2898FC62B9CF4E62 ON events_list (event_category_id)');
        $this->addSql('CREATE INDEX IDX_2898FC62195DA277 ON events_list (event_level_id)');
        $this->addSql('CREATE INDEX IDX_2898FC624B4A4BC9 ON events_list (event_place_id)');
        $this->addSql('CREATE TABLE events_list_staff (events_list_id INT NOT NULL, staff_id INT NOT NULL, PRIMARY KEY(events_list_id, staff_id))');
        $this->addSql('CREATE INDEX IDX_4E04D2106BCF6F91 ON events_list_staff (events_list_id)');
        $this->addSql('CREATE INDEX IDX_4E04D210D4D57CD ON events_list_staff (staff_id)');
        $this->addSql('CREATE TABLE events_list_student (events_list_id INT NOT NULL, student_id INT NOT NULL, PRIMARY KEY(events_list_id, student_id))');
        $this->addSql('CREATE INDEX IDX_F2FF49CE6BCF6F91 ON events_list_student (events_list_id)');
        $this->addSql('CREATE INDEX IDX_F2FF49CECB944F1A ON events_list_student (student_id)');
        $this->addSql('CREATE TABLE events_places (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE events_result (id INT NOT NULL, event_id INT DEFAULT NULL, student_id INT DEFAULT NULL, result_type_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C1D7F82671F7E88B ON events_result (event_id)');
        $this->addSql('CREATE INDEX IDX_C1D7F826CB944F1A ON events_result (student_id)');
        $this->addSql('CREATE INDEX IDX_C1D7F826A7750E77 ON events_result (result_type_id)');
        $this->addSql('CREATE TABLE events_result_types (id INT NOT NULL, name VARCHAR(255) NOT NULL, is_winner BOOLEAN NOT NULL, is_awarded BOOLEAN NOT NULL, is_participant BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE faculty (id INT NOT NULL, specialization_id INT DEFAULT NULL, education_type_id INT DEFAULT NULL, education_form_id INT DEFAULT NULL, financial_type_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_17966043FA846217 ON faculty (specialization_id)');
        $this->addSql('CREATE INDEX IDX_17966043D968E34B ON faculty (education_type_id)');
        $this->addSql('CREATE INDEX IDX_1796604343D2F4A5 ON faculty (education_form_id)');
        $this->addSql('CREATE INDEX IDX_17966043978FCEF9 ON faculty (financial_type_id)');
        $this->addSql('CREATE TABLE family_type_list (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE financial_type (id INT NOT NULL, name VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE gender (id INT NOT NULL, name VARCHAR(255) NOT NULL, gender_name VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE group_membership (id INT NOT NULL, student_id INT DEFAULT NULL, student_group_id INT DEFAULT NULL, contingent_document_id INT DEFAULT NULL, date_start DATE DEFAULT NULL, date_end DATE DEFAULT NULL, active BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5132B337CB944F1A ON group_membership (student_id)');
        $this->addSql('CREATE INDEX IDX_5132B3374DDF95DC ON group_membership (student_group_id)');
        $this->addSql('CREATE INDEX IDX_5132B33718B26CAF ON group_membership (contingent_document_id)');
        $this->addSql('CREATE TABLE health_group (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE legal_representative (id INT NOT NULL, representatives_type_id INT DEFAULT NULL, student_id_id INT DEFAULT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, middle_name VARCHAR(255) DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, comment TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E48926AD3B8760F6 ON legal_representative (representatives_type_id)');
        $this->addSql('CREATE INDEX IDX_E48926ADF773E7CA ON legal_representative (student_id_id)');
        $this->addSql('CREATE TABLE legal_representative_type_list (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE login_provider (id INT NOT NULL, title VARCHAR(255) NOT NULL, login_key VARCHAR(255) NOT NULL, password_key VARCHAR(255) NOT NULL, auth_path VARCHAR(255) NOT NULL, custom_params VARCHAR(255) DEFAULT NULL, user_can_login BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE login_values (id INT NOT NULL, student_id INT DEFAULT NULL, login_provider_id INT DEFAULT NULL, login_value VARCHAR(255) NOT NULL, password_value VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_CDC36B7CCB944F1A ON login_values (student_id)');
        $this->addSql('CREATE INDEX IDX_CDC36B7CB823141A ON login_values (login_provider_id)');
        $this->addSql('CREATE TABLE mod_mosreg_vis (id INT NOT NULL, mosreg_viscollege_id INT DEFAULT NULL, username VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, org_id VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_30ECAF459AEC9EA4 ON mod_mosreg_vis (mosreg_viscollege_id)');
        $this->addSql('CREATE TABLE person (id INT NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, middle_name VARCHAR(255) DEFAULT NULL, inn VARCHAR(12) DEFAULT NULL, snils VARCHAR(14) NOT NULL, medical_series VARCHAR(6) DEFAULT NULL, medical_number VARCHAR(20) DEFAULT NULL, birth_place TEXT DEFAULT NULL, medical_date_issue DATE DEFAULT NULL, birth_date DATE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE personal_doc_type_list (id INT NOT NULL, name VARCHAR(255) NOT NULL, title VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE personal_documents (id INT NOT NULL, document_type_id INT DEFAULT NULL, student_id INT DEFAULT NULL, document_series VARCHAR(20) DEFAULT NULL, document_number VARCHAR(255) DEFAULT NULL, document_issue_date DATE DEFAULT NULL, document_official_seal TEXT DEFAULT NULL, comment TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_AD1CB46261232A4F ON personal_documents (document_type_id)');
        $this->addSql('CREATE INDEX IDX_AD1CB462CB944F1A ON personal_documents (student_id)');
        $this->addSql('CREATE TABLE reference_edu_year_status (id INT NOT NULL, code INT NOT NULL, name VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE reference_spo_education_year (id INT NOT NULL, year_status_id INT DEFAULT NULL, admisson_id INT DEFAULT NULL, college_id INT DEFAULT NULL, guid VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, start_date DATE DEFAULT NULL, end_date DATE DEFAULT NULL, order_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_33F2621356065E0C ON reference_spo_education_year (year_status_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_33F2621349F4482A ON reference_spo_education_year (admisson_id)');
        $this->addSql('CREATE INDEX IDX_33F26213770124B2 ON reference_spo_education_year (college_id)');
        $this->addSql('CREATE TABLE reference_spo_speciality_dictionary (id INT NOT NULL, training_program_gradation_id INT DEFAULT NULL, code VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, qualification TEXT NOT NULL, id_vis INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_96632C67C9927855 ON reference_spo_speciality_dictionary (training_program_gradation_id)');
        $this->addSql('CREATE TABLE reference_study_discipline (id INT NOT NULL, id_vis INT NOT NULL, name VARCHAR(255) NOT NULL, discipline_group VARCHAR(255) DEFAULT NULL, is_spo BOOLEAN NOT NULL, is_school BOOLEAN NOT NULL, is_odo BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE reference_training_program_gradation (id INT NOT NULL, name VARCHAR(255) NOT NULL, abbr VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE reference_uftt_document_type (id INT NOT NULL, name VARCHAR(255) NOT NULL, code VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE regions (id INT NOT NULL, name VARCHAR(255) NOT NULL, code INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE roles (id INT NOT NULL, name VARCHAR(255) NOT NULL, role_name VARCHAR(255) NOT NULL, status BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE social_network (id INT NOT NULL, studetn_id_id INT DEFAULT NULL, social_network_type_id_id INT DEFAULT NULL, social_network_link VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_EFFF5221D9A609A9 ON social_network (studetn_id_id)');
        $this->addSql('CREATE INDEX IDX_EFFF5221FB4FD43C ON social_network (social_network_type_id_id)');
        $this->addSql('CREATE TABLE social_network_type_list (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE specialization (id INT NOT NULL, name VARCHAR(255) NOT NULL, code VARCHAR(255) NOT NULL, group_suffix VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE staff (id INT NOT NULL, person_id INT DEFAULT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, middle_name VARCHAR(255) DEFAULT NULL, photo TEXT DEFAULT NULL, uuid VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_426EF392217BBB47 ON staff (person_id)');
        $this->addSql('CREATE TABLE staff_college (staff_id INT NOT NULL, college_id INT NOT NULL, PRIMARY KEY(staff_id, college_id))');
        $this->addSql('CREATE INDEX IDX_F66C90B4D4D57CD ON staff_college (staff_id)');
        $this->addSql('CREATE INDEX IDX_F66C90B4770124B2 ON staff_college (college_id)');
        $this->addSql('CREATE TABLE student (id INT NOT NULL, family_type_id_id INT DEFAULT NULL, healtg_group_id_id INT DEFAULT NULL, gender_id INT DEFAULT NULL, student_group_id INT DEFAULT NULL, abiturient_petition_id INT DEFAULT NULL, person_id INT DEFAULT NULL, number_zachetka VARCHAR(10) DEFAULT NULL, number_stud_bilet VARCHAR(10) DEFAULT NULL, phone_number VARCHAR(255) NOT NULL, email VARCHAR(255) DEFAULT NULL, document_medical_id VARCHAR(255) DEFAULT NULL, address_fact TEXT DEFAULT NULL, address_main TEXT DEFAULT NULL, is_active BOOLEAN DEFAULT NULL, photo TEXT DEFAULT NULL, is_orphan BOOLEAN DEFAULT NULL, is_paid BOOLEAN DEFAULT NULL, is_invalid BOOLEAN DEFAULT NULL, is_poor BOOLEAN DEFAULT NULL, pasport_number INT DEFAULT NULL, pasport_series VARCHAR(255) DEFAULT NULL, pasport_date DATE DEFAULT NULL, pasport_issue_organ TEXT DEFAULT NULL, is_without_parents BOOLEAN DEFAULT NULL, first_password VARCHAR(255) DEFAULT NULL, uuid VARCHAR(255) DEFAULT NULL, is_live_student_accommondation BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B723AF334282CADF ON student (family_type_id_id)');
        $this->addSql('CREATE INDEX IDX_B723AF33A6BC37B ON student (healtg_group_id_id)');
        $this->addSql('CREATE INDEX IDX_B723AF33708A0E0 ON student (gender_id)');
        $this->addSql('CREATE INDEX IDX_B723AF334DDF95DC ON student (student_group_id)');
        $this->addSql('CREATE INDEX IDX_B723AF33821E040B ON student (abiturient_petition_id)');
        $this->addSql('CREATE INDEX IDX_B723AF33217BBB47 ON student (person_id)');
        $this->addSql('CREATE TABLE student_groups (id INT NOT NULL, faculty_id INT DEFAULT NULL, group_leader_id INT DEFAULT NULL, education_plan_id INT DEFAULT NULL, name VARCHAR(12) NOT NULL, code VARCHAR(255) DEFAULT NULL, date_start DATE DEFAULT NULL, data_end DATE DEFAULT NULL, course_number INT DEFAULT NULL, parallel_number INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7E5BE1F0680CAB68 ON student_groups (faculty_id)');
        $this->addSql('CREATE INDEX IDX_7E5BE1F0B3A61235 ON student_groups (group_leader_id)');
        $this->addSql('CREATE INDEX IDX_7E5BE1F0F4BD6D43 ON student_groups (education_plan_id)');
        $this->addSql('CREATE TABLE student_punishment (id INT NOT NULL, student_id INT DEFAULT NULL, date DATE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_96D5ABD0CB944F1A ON student_punishment (student_id)');
        $this->addSql('CREATE TABLE system_services (id INT NOT NULL, title VARCHAR(255) NOT NULL, system_name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE "user" (id INT NOT NULL, student_id INT DEFAULT NULL, staff_id INT DEFAULT NULL, college_id INT DEFAULT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, is_student BOOLEAN DEFAULT NULL, userphoto TEXT DEFAULT NULL, front_end_params JSON DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649CB944F1A ON "user" (student_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649D4D57CD ON "user" (staff_id)');
        $this->addSql('CREATE INDEX IDX_8D93D649770124B2 ON "user" (college_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGSERIAL NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('COMMENT ON COLUMN messenger_messages.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.available_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.delivered_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE OR REPLACE FUNCTION notify_messenger_messages() RETURNS TRIGGER AS $$
            BEGIN
                PERFORM pg_notify(\'messenger_messages\', NEW.queue_name::text);
                RETURN NEW;
            END;
        $$ LANGUAGE plpgsql;');
        $this->addSql('DROP TRIGGER IF EXISTS notify_trigger ON messenger_messages;');
        $this->addSql('CREATE TRIGGER notify_trigger AFTER INSERT OR UPDATE ON messenger_messages FOR EACH ROW EXECUTE PROCEDURE notify_messenger_messages();');
        $this->addSql('ALTER TABLE abiturient_petition ADD CONSTRAINT FK_50A0C6E5708A0E0 FOREIGN KEY (gender_id) REFERENCES gender (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE abiturient_petition ADD CONSTRAINT FK_50A0C6E56BF700BD FOREIGN KEY (status_id) REFERENCES abiturient_petition_status (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE abiturient_petition ADD CONSTRAINT FK_50A0C6E575C9C554 FOREIGN KEY (admission_id) REFERENCES admission (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE abiturient_petition ADD CONSTRAINT FK_50A0C6E5680CAB68 FOREIGN KEY (faculty_id) REFERENCES faculty (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE abiturient_petition ADD CONSTRAINT FK_50A0C6E598260155 FOREIGN KEY (region_id) REFERENCES regions (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE abiturient_petition ADD CONSTRAINT FK_50A0C6E54452387F FOREIGN KEY (admission_plan_position_id) REFERENCES admission_plan (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE abiturient_petition ADD CONSTRAINT FK_50A0C6E5217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE access_system_control ADD CONSTRAINT FK_3D33BA65CB944F1A FOREIGN KEY (student_id) REFERENCES student (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE admission ADD CONSTRAINT FK_F4BB024A6BF700BD FOREIGN KEY (status_id) REFERENCES admission_status (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE admission ADD CONSTRAINT FK_F4BB024A770124B2 FOREIGN KEY (college_id) REFERENCES college (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE admission_examination ADD CONSTRAINT FK_AD531D33680CAB68 FOREIGN KEY (faculty_id) REFERENCES faculty (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE admission_examination ADD CONSTRAINT FK_AD531D334C13C434 FOREIGN KEY (examination_subject_id) REFERENCES admission_examination_subjects (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE admission_examination ADD CONSTRAINT FK_AD531D334452387F FOREIGN KEY (admission_plan_position_id) REFERENCES admission_plan (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE admission_examination_result ADD CONSTRAINT FK_C28FCD9821E040B FOREIGN KEY (abiturient_petition_id) REFERENCES abiturient_petition (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE admission_examination_result ADD CONSTRAINT FK_C28FCD94D62F206 FOREIGN KEY (admission_examination_id) REFERENCES admission_examination (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE admission_plan ADD CONSTRAINT FK_81EE964D75C9C554 FOREIGN KEY (admission_id) REFERENCES admission (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE admission_plan ADD CONSTRAINT FK_81EE964D680CAB68 FOREIGN KEY (faculty_id) REFERENCES faculty (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE characteristic ADD CONSTRAINT FK_522FA950CB944F1A FOREIGN KEY (student_id) REFERENCES student (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contingent_document ADD CONSTRAINT FK_672BE59BC54C8C93 FOREIGN KEY (type_id) REFERENCES contingent_document_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contingent_document ADD CONSTRAINT FK_672BE59B770124B2 FOREIGN KEY (college_id) REFERENCES college (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contingent_document_student ADD CONSTRAINT FK_A66031F118B26CAF FOREIGN KEY (contingent_document_id) REFERENCES contingent_document (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contingent_document_student ADD CONSTRAINT FK_A66031F1CB944F1A FOREIGN KEY (student_id) REFERENCES student (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE education_plan ADD CONSTRAINT FK_37C3E6CC680CAB68 FOREIGN KEY (faculty_id) REFERENCES faculty (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE education_plan ADD CONSTRAINT FK_37C3E6CC43D2F4A5 FOREIGN KEY (education_form_id) REFERENCES education_form (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE education_plan ADD CONSTRAINT FK_37C3E6CC7FE0B941 FOREIGN KEY (base_education_type_id) REFERENCES education_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE education_semester ADD CONSTRAINT FK_7F2CF0645CE5917F FOREIGN KEY (education_year_id) REFERENCES education_year (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE education_semester ADD CONSTRAINT FK_7F2CF064F4BD6D43 FOREIGN KEY (education_plan_id) REFERENCES education_plan (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE events_list ADD CONSTRAINT FK_2898FC62B9CF4E62 FOREIGN KEY (event_category_id) REFERENCES events_category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE events_list ADD CONSTRAINT FK_2898FC62195DA277 FOREIGN KEY (event_level_id) REFERENCES events_level (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE events_list ADD CONSTRAINT FK_2898FC624B4A4BC9 FOREIGN KEY (event_place_id) REFERENCES events_places (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE events_list_staff ADD CONSTRAINT FK_4E04D2106BCF6F91 FOREIGN KEY (events_list_id) REFERENCES events_list (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE events_list_staff ADD CONSTRAINT FK_4E04D210D4D57CD FOREIGN KEY (staff_id) REFERENCES staff (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE events_list_student ADD CONSTRAINT FK_F2FF49CE6BCF6F91 FOREIGN KEY (events_list_id) REFERENCES events_list (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE events_list_student ADD CONSTRAINT FK_F2FF49CECB944F1A FOREIGN KEY (student_id) REFERENCES student (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE events_result ADD CONSTRAINT FK_C1D7F82671F7E88B FOREIGN KEY (event_id) REFERENCES events_list (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE events_result ADD CONSTRAINT FK_C1D7F826CB944F1A FOREIGN KEY (student_id) REFERENCES student (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE events_result ADD CONSTRAINT FK_C1D7F826A7750E77 FOREIGN KEY (result_type_id) REFERENCES events_result_types (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE faculty ADD CONSTRAINT FK_17966043FA846217 FOREIGN KEY (specialization_id) REFERENCES specialization (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE faculty ADD CONSTRAINT FK_17966043D968E34B FOREIGN KEY (education_type_id) REFERENCES education_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE faculty ADD CONSTRAINT FK_1796604343D2F4A5 FOREIGN KEY (education_form_id) REFERENCES education_form (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE faculty ADD CONSTRAINT FK_17966043978FCEF9 FOREIGN KEY (financial_type_id) REFERENCES financial_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE group_membership ADD CONSTRAINT FK_5132B337CB944F1A FOREIGN KEY (student_id) REFERENCES student (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE group_membership ADD CONSTRAINT FK_5132B3374DDF95DC FOREIGN KEY (student_group_id) REFERENCES student_groups (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE group_membership ADD CONSTRAINT FK_5132B33718B26CAF FOREIGN KEY (contingent_document_id) REFERENCES contingent_document (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE legal_representative ADD CONSTRAINT FK_E48926AD3B8760F6 FOREIGN KEY (representatives_type_id) REFERENCES legal_representative_type_list (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE legal_representative ADD CONSTRAINT FK_E48926ADF773E7CA FOREIGN KEY (student_id_id) REFERENCES student (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE login_values ADD CONSTRAINT FK_CDC36B7CCB944F1A FOREIGN KEY (student_id) REFERENCES student (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE login_values ADD CONSTRAINT FK_CDC36B7CB823141A FOREIGN KEY (login_provider_id) REFERENCES login_provider (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE mod_mosreg_vis ADD CONSTRAINT FK_30ECAF459AEC9EA4 FOREIGN KEY (mosreg_viscollege_id) REFERENCES college (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE personal_documents ADD CONSTRAINT FK_AD1CB46261232A4F FOREIGN KEY (document_type_id) REFERENCES personal_doc_type_list (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE personal_documents ADD CONSTRAINT FK_AD1CB462CB944F1A FOREIGN KEY (student_id) REFERENCES student (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reference_spo_education_year ADD CONSTRAINT FK_33F2621356065E0C FOREIGN KEY (year_status_id) REFERENCES reference_edu_year_status (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reference_spo_education_year ADD CONSTRAINT FK_33F2621349F4482A FOREIGN KEY (admisson_id) REFERENCES admission (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reference_spo_education_year ADD CONSTRAINT FK_33F26213770124B2 FOREIGN KEY (college_id) REFERENCES college (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reference_spo_speciality_dictionary ADD CONSTRAINT FK_96632C67C9927855 FOREIGN KEY (training_program_gradation_id) REFERENCES reference_training_program_gradation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE social_network ADD CONSTRAINT FK_EFFF5221D9A609A9 FOREIGN KEY (studetn_id_id) REFERENCES student (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE social_network ADD CONSTRAINT FK_EFFF5221FB4FD43C FOREIGN KEY (social_network_type_id_id) REFERENCES social_network_type_list (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE staff ADD CONSTRAINT FK_426EF392217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE staff_college ADD CONSTRAINT FK_F66C90B4D4D57CD FOREIGN KEY (staff_id) REFERENCES staff (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE staff_college ADD CONSTRAINT FK_F66C90B4770124B2 FOREIGN KEY (college_id) REFERENCES college (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student ADD CONSTRAINT FK_B723AF334282CADF FOREIGN KEY (family_type_id_id) REFERENCES family_type_list (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student ADD CONSTRAINT FK_B723AF33A6BC37B FOREIGN KEY (healtg_group_id_id) REFERENCES health_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student ADD CONSTRAINT FK_B723AF33708A0E0 FOREIGN KEY (gender_id) REFERENCES gender (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student ADD CONSTRAINT FK_B723AF334DDF95DC FOREIGN KEY (student_group_id) REFERENCES student_groups (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student ADD CONSTRAINT FK_B723AF33821E040B FOREIGN KEY (abiturient_petition_id) REFERENCES abiturient_petition (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student ADD CONSTRAINT FK_B723AF33217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student_groups ADD CONSTRAINT FK_7E5BE1F0680CAB68 FOREIGN KEY (faculty_id) REFERENCES faculty (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student_groups ADD CONSTRAINT FK_7E5BE1F0B3A61235 FOREIGN KEY (group_leader_id) REFERENCES staff (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student_groups ADD CONSTRAINT FK_7E5BE1F0F4BD6D43 FOREIGN KEY (education_plan_id) REFERENCES education_plan (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student_punishment ADD CONSTRAINT FK_96D5ABD0CB944F1A FOREIGN KEY (student_id) REFERENCES student (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649CB944F1A FOREIGN KEY (student_id) REFERENCES student (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649D4D57CD FOREIGN KEY (staff_id) REFERENCES staff (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649770124B2 FOREIGN KEY (college_id) REFERENCES college (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('DROP SEQUENCE abiturient_petition_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE abiturient_petition_status_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE access_system_control_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE admission_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE admission_examination_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE admission_examination_result_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE admission_examination_subjects_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE admission_plan_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE admission_status_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE app_configuration_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE characteristic_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE college_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE contingent_document_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE contingent_document_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE education_form_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE education_plan_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE education_semester_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE education_subjects_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE education_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE education_year_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE events_category_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE events_level_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE events_list_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE events_places_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE events_result_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE events_result_types_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE faculty_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE family_type_list_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE financial_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE gender_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE group_membership_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE health_group_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE legal_representative_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE legal_representative_type_list_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE login_provider_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE login_values_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE mod_mosreg_vis_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE person_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE personal_doc_type_list_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE personal_documents_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE reference_edu_year_status_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE reference_spo_education_year_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE reference_spo_speciality_dictionary_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE reference_study_discipline_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE reference_training_program_gradation_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE reference_uftt_document_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE regions_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE roles_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE social_network_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE social_network_type_list_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE specialization_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE staff_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE student_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE student_groups_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE student_punishment_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE system_services_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE "user_id_seq" CASCADE');
        $this->addSql('ALTER TABLE abiturient_petition DROP CONSTRAINT FK_50A0C6E5708A0E0');
        $this->addSql('ALTER TABLE abiturient_petition DROP CONSTRAINT FK_50A0C6E56BF700BD');
        $this->addSql('ALTER TABLE abiturient_petition DROP CONSTRAINT FK_50A0C6E575C9C554');
        $this->addSql('ALTER TABLE abiturient_petition DROP CONSTRAINT FK_50A0C6E5680CAB68');
        $this->addSql('ALTER TABLE abiturient_petition DROP CONSTRAINT FK_50A0C6E598260155');
        $this->addSql('ALTER TABLE abiturient_petition DROP CONSTRAINT FK_50A0C6E54452387F');
        $this->addSql('ALTER TABLE abiturient_petition DROP CONSTRAINT FK_50A0C6E5217BBB47');
        $this->addSql('ALTER TABLE access_system_control DROP CONSTRAINT FK_3D33BA65CB944F1A');
        $this->addSql('ALTER TABLE admission DROP CONSTRAINT FK_F4BB024A6BF700BD');
        $this->addSql('ALTER TABLE admission DROP CONSTRAINT FK_F4BB024A770124B2');
        $this->addSql('ALTER TABLE admission_examination DROP CONSTRAINT FK_AD531D33680CAB68');
        $this->addSql('ALTER TABLE admission_examination DROP CONSTRAINT FK_AD531D334C13C434');
        $this->addSql('ALTER TABLE admission_examination DROP CONSTRAINT FK_AD531D334452387F');
        $this->addSql('ALTER TABLE admission_examination_result DROP CONSTRAINT FK_C28FCD9821E040B');
        $this->addSql('ALTER TABLE admission_examination_result DROP CONSTRAINT FK_C28FCD94D62F206');
        $this->addSql('ALTER TABLE admission_plan DROP CONSTRAINT FK_81EE964D75C9C554');
        $this->addSql('ALTER TABLE admission_plan DROP CONSTRAINT FK_81EE964D680CAB68');
        $this->addSql('ALTER TABLE characteristic DROP CONSTRAINT FK_522FA950CB944F1A');
        $this->addSql('ALTER TABLE contingent_document DROP CONSTRAINT FK_672BE59BC54C8C93');
        $this->addSql('ALTER TABLE contingent_document DROP CONSTRAINT FK_672BE59B770124B2');
        $this->addSql('ALTER TABLE contingent_document_student DROP CONSTRAINT FK_A66031F118B26CAF');
        $this->addSql('ALTER TABLE contingent_document_student DROP CONSTRAINT FK_A66031F1CB944F1A');
        $this->addSql('ALTER TABLE education_plan DROP CONSTRAINT FK_37C3E6CC680CAB68');
        $this->addSql('ALTER TABLE education_plan DROP CONSTRAINT FK_37C3E6CC43D2F4A5');
        $this->addSql('ALTER TABLE education_plan DROP CONSTRAINT FK_37C3E6CC7FE0B941');
        $this->addSql('ALTER TABLE education_semester DROP CONSTRAINT FK_7F2CF0645CE5917F');
        $this->addSql('ALTER TABLE education_semester DROP CONSTRAINT FK_7F2CF064F4BD6D43');
        $this->addSql('ALTER TABLE events_list DROP CONSTRAINT FK_2898FC62B9CF4E62');
        $this->addSql('ALTER TABLE events_list DROP CONSTRAINT FK_2898FC62195DA277');
        $this->addSql('ALTER TABLE events_list DROP CONSTRAINT FK_2898FC624B4A4BC9');
        $this->addSql('ALTER TABLE events_list_staff DROP CONSTRAINT FK_4E04D2106BCF6F91');
        $this->addSql('ALTER TABLE events_list_staff DROP CONSTRAINT FK_4E04D210D4D57CD');
        $this->addSql('ALTER TABLE events_list_student DROP CONSTRAINT FK_F2FF49CE6BCF6F91');
        $this->addSql('ALTER TABLE events_list_student DROP CONSTRAINT FK_F2FF49CECB944F1A');
        $this->addSql('ALTER TABLE events_result DROP CONSTRAINT FK_C1D7F82671F7E88B');
        $this->addSql('ALTER TABLE events_result DROP CONSTRAINT FK_C1D7F826CB944F1A');
        $this->addSql('ALTER TABLE events_result DROP CONSTRAINT FK_C1D7F826A7750E77');
        $this->addSql('ALTER TABLE faculty DROP CONSTRAINT FK_17966043FA846217');
        $this->addSql('ALTER TABLE faculty DROP CONSTRAINT FK_17966043D968E34B');
        $this->addSql('ALTER TABLE faculty DROP CONSTRAINT FK_1796604343D2F4A5');
        $this->addSql('ALTER TABLE faculty DROP CONSTRAINT FK_17966043978FCEF9');
        $this->addSql('ALTER TABLE group_membership DROP CONSTRAINT FK_5132B337CB944F1A');
        $this->addSql('ALTER TABLE group_membership DROP CONSTRAINT FK_5132B3374DDF95DC');
        $this->addSql('ALTER TABLE group_membership DROP CONSTRAINT FK_5132B33718B26CAF');
        $this->addSql('ALTER TABLE legal_representative DROP CONSTRAINT FK_E48926AD3B8760F6');
        $this->addSql('ALTER TABLE legal_representative DROP CONSTRAINT FK_E48926ADF773E7CA');
        $this->addSql('ALTER TABLE login_values DROP CONSTRAINT FK_CDC36B7CCB944F1A');
        $this->addSql('ALTER TABLE login_values DROP CONSTRAINT FK_CDC36B7CB823141A');
        $this->addSql('ALTER TABLE mod_mosreg_vis DROP CONSTRAINT FK_30ECAF459AEC9EA4');
        $this->addSql('ALTER TABLE personal_documents DROP CONSTRAINT FK_AD1CB46261232A4F');
        $this->addSql('ALTER TABLE personal_documents DROP CONSTRAINT FK_AD1CB462CB944F1A');
        $this->addSql('ALTER TABLE reference_spo_education_year DROP CONSTRAINT FK_33F2621356065E0C');
        $this->addSql('ALTER TABLE reference_spo_education_year DROP CONSTRAINT FK_33F2621349F4482A');
        $this->addSql('ALTER TABLE reference_spo_education_year DROP CONSTRAINT FK_33F26213770124B2');
        $this->addSql('ALTER TABLE reference_spo_speciality_dictionary DROP CONSTRAINT FK_96632C67C9927855');
        $this->addSql('ALTER TABLE social_network DROP CONSTRAINT FK_EFFF5221D9A609A9');
        $this->addSql('ALTER TABLE social_network DROP CONSTRAINT FK_EFFF5221FB4FD43C');
        $this->addSql('ALTER TABLE staff DROP CONSTRAINT FK_426EF392217BBB47');
        $this->addSql('ALTER TABLE staff_college DROP CONSTRAINT FK_F66C90B4D4D57CD');
        $this->addSql('ALTER TABLE staff_college DROP CONSTRAINT FK_F66C90B4770124B2');
        $this->addSql('ALTER TABLE student DROP CONSTRAINT FK_B723AF334282CADF');
        $this->addSql('ALTER TABLE student DROP CONSTRAINT FK_B723AF33A6BC37B');
        $this->addSql('ALTER TABLE student DROP CONSTRAINT FK_B723AF33708A0E0');
        $this->addSql('ALTER TABLE student DROP CONSTRAINT FK_B723AF334DDF95DC');
        $this->addSql('ALTER TABLE student DROP CONSTRAINT FK_B723AF33821E040B');
        $this->addSql('ALTER TABLE student DROP CONSTRAINT FK_B723AF33217BBB47');
        $this->addSql('ALTER TABLE student_groups DROP CONSTRAINT FK_7E5BE1F0680CAB68');
        $this->addSql('ALTER TABLE student_groups DROP CONSTRAINT FK_7E5BE1F0B3A61235');
        $this->addSql('ALTER TABLE student_groups DROP CONSTRAINT FK_7E5BE1F0F4BD6D43');
        $this->addSql('ALTER TABLE student_punishment DROP CONSTRAINT FK_96D5ABD0CB944F1A');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649CB944F1A');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649D4D57CD');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649770124B2');
        $this->addSql('DROP TABLE abiturient_petition');
        $this->addSql('DROP TABLE abiturient_petition_status');
        $this->addSql('DROP TABLE access_system_control');
        $this->addSql('DROP TABLE admission');
        $this->addSql('DROP TABLE admission_examination');
        $this->addSql('DROP TABLE admission_examination_result');
        $this->addSql('DROP TABLE admission_examination_subjects');
        $this->addSql('DROP TABLE admission_plan');
        $this->addSql('DROP TABLE admission_status');
        $this->addSql('DROP TABLE app_configuration');
        $this->addSql('DROP TABLE characteristic');
        $this->addSql('DROP TABLE college');
        $this->addSql('DROP TABLE contingent_document');
        $this->addSql('DROP TABLE contingent_document_student');
        $this->addSql('DROP TABLE contingent_document_type');
        $this->addSql('DROP TABLE education_form');
        $this->addSql('DROP TABLE education_plan');
        $this->addSql('DROP TABLE education_semester');
        $this->addSql('DROP TABLE education_subjects');
        $this->addSql('DROP TABLE education_type');
        $this->addSql('DROP TABLE education_year');
        $this->addSql('DROP TABLE events_category');
        $this->addSql('DROP TABLE events_level');
        $this->addSql('DROP TABLE events_list');
        $this->addSql('DROP TABLE events_list_staff');
        $this->addSql('DROP TABLE events_list_student');
        $this->addSql('DROP TABLE events_places');
        $this->addSql('DROP TABLE events_result');
        $this->addSql('DROP TABLE events_result_types');
        $this->addSql('DROP TABLE faculty');
        $this->addSql('DROP TABLE family_type_list');
        $this->addSql('DROP TABLE financial_type');
        $this->addSql('DROP TABLE gender');
        $this->addSql('DROP TABLE group_membership');
        $this->addSql('DROP TABLE health_group');
        $this->addSql('DROP TABLE legal_representative');
        $this->addSql('DROP TABLE legal_representative_type_list');
        $this->addSql('DROP TABLE login_provider');
        $this->addSql('DROP TABLE login_values');
        $this->addSql('DROP TABLE mod_mosreg_vis');
        $this->addSql('DROP TABLE person');
        $this->addSql('DROP TABLE personal_doc_type_list');
        $this->addSql('DROP TABLE personal_documents');
        $this->addSql('DROP TABLE reference_edu_year_status');
        $this->addSql('DROP TABLE reference_spo_education_year');
        $this->addSql('DROP TABLE reference_spo_speciality_dictionary');
        $this->addSql('DROP TABLE reference_study_discipline');
        $this->addSql('DROP TABLE reference_training_program_gradation');
        $this->addSql('DROP TABLE reference_uftt_document_type');
        $this->addSql('DROP TABLE regions');
        $this->addSql('DROP TABLE roles');
        $this->addSql('DROP TABLE social_network');
        $this->addSql('DROP TABLE social_network_type_list');
        $this->addSql('DROP TABLE specialization');
        $this->addSql('DROP TABLE staff');
        $this->addSql('DROP TABLE staff_college');
        $this->addSql('DROP TABLE student');
        $this->addSql('DROP TABLE student_groups');
        $this->addSql('DROP TABLE student_punishment');
        $this->addSql('DROP TABLE system_services');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
