controllers:
    resource:
        path: ../App/
        namespace: App\
    type: attribute

kernel:
    resource: ../App/Kernel.php
    type: attribute

api_login_check:
    path: /api/login/check
api_login_refresh:
    path: /api/login/refresh

mosreg_vis_api:
    resource: 'routes/mod_mosreg_vis.yaml'
    name_prefix: 'mod_mosreg_vis'